name: Start a run from Jupyter Notebook on local server via self-hosted Github Actions runner

on:
  push:
    branches:
      - development

jobs:
  start-local-run:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2

    - name: Check Python version
      run: |
        which python
        python --version
        
    - name: Inspect environment
      run: |
        env
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        
    - name: Create and activate virtual environment
      run: |
        python -m venv env
        source env/bin/activate
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install jupyter
        
    - name: Connect to local server and run the Notebook
      run: |       
        # Execute the Jupyter Notebook and overwrite the existing file with the results
        jupyter nbconvert --execute --to notebook --inplace path/to/demo-pipeline.ipynb
        
    - name: Deactivate virtual environment
      run: deactivate
