name: Start a run from Jupyter Notebook on local server via self-hosted Github Actions runner

on:
  push:
    branches:
      - development

jobs:
  start-local-run:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py
        pip install --upgrade pip
        pip install jupyter
        
    - name: Connect to local server and run the Notebook
      run: |       
        # Execute the Jupyter Notebook and overwrite the existing file with the results
        jupyter nbconvert --execute --to notebook --inplace notebooks/local/demo-pipeline.ipynb
